### ISSUE TITLE
PyWrapper Compilation Error

### ISSUE THREAD

**Issue by AmeyHande** [kctess5/range_libc#4]
Hello Everyone,
I'm trying to use Range Libc package on NVIDIA Jetson Xavier, just like MIT Racecar configuration.
But after following your procedure to install it on Racecar Configuration, while installing pywrapper.
I'm getting this error,
`/usr/local/cuda/bin/nvcc -I../ -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/cuda/include -I/usr/include/python2.7 -c ../includes/kernels.cu -o build/temp.linux-aarch64-2.7/../includes/kernels.o -arch=sm_20 --ptxas-options=-v -c --compiler-options '-fPIC' -w -std=c++11 -DUSE_CUDA=1 -DCHUNK_SIZE=262144 -DNUM_THREADS=256
nvcc fatal   : Value 'sm_20' is not defined for option 'gpu-architecture'
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
`
Does anyone have any solutions to this issue?

Thank You,
Amey Hande

**Comment by AmeyHande** [comment]
I think I have solution of it by changing value of `-arch=sm_20`
 in setup.py on line 96 `nvcc_flags` = ['-arch=sm_20', '--ptxas-options=-v', '-c', '--compiler-options', "'-fPIC'", "-w","-std=c++11"]` to `-arch=sm_30`, which was one of the acceptable options in gpu-architecture.
It would be great, if someone who has worked on this gives some guidance whether my correction method is right or not. As after that it compiled successfully, but till now haven't got chance to test it's working.
Thank You,
Amey Hande

**Comment by MTDzi** [comment]
Hey,

I had the same issue, and your solution worked.

I think you can now close this Issue ;)
